version: '3.8'

services:
  postgres:
    container_name: db_postgres
    image: pgvector/pgvector:pg16
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: job_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: job_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  job_scraper:
    build:
      context: .
      dockerfile: jobsearchsubul/Dockerfile
    container_name: job_scraper
    depends_on:
      - kafka

  job_consumer:
    build:
      context: .
      dockerfile: jobsearchsubul/Dockerfile
    container_name: job_consumer
    command: ["python3", "jobsearchsubul/tools/consumer.py"]


    depends_on:
      - kafka
      - postgres
    env_file:
      - .env

  airflow-init:
    container_name: job_airflow-init
    image: apache/airflow:2.9.1
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:2024@postgres:5432/dbairflow
    entrypoint: 
      bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    volumes:
      - ./jobsearchsubul/airflow/dags:/opt/airflow/dags
      - ./jobsearchsubul/tools:/opt/airflow/tools



  airflow-webserver:
    container_name: job_airflow-webserver
    image: apache/airflow:2.9.1
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:2024@postgres:5432/dbairflow

    volumes:
      - ./jobsearchsubul/airflow/dags:/opt/airflow/dags
      - ./jobsearchsubul/tools:/opt/airflow/tools
    command: webserver


  airflow-scheduler:
    container_name: job_airflow-scheduler
    image: apache/airflow:2.9.1
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:2024@postgres:5432/dbairflow
    volumes:
      - ./jobsearchsubul/airflow/dags:/opt/airflow/dags
      - ./jobsearchsubul/tools:/opt/airflow/tools
    command: scheduler




volumes:
  postgres_data:
