# docker-compose.yml

services:
  postgres:
    container_name: db_postgres
    image: pgvector/pgvector:pg16
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: job_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: job_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  job_scraper:
    build:
      context: .
      dockerfile: jobsearchsubul/Dockerfile
    container_name: job_scraper
    working_dir: /app
    depends_on:
      - kafka
    volumes:
      - ./jobsearchsubul:/app/jobsearchsubul
      - ./backend:/app/backend

  job_consumer:
    build:
      context: .
      dockerfile: jobsearchsubul/Dockerfile
    container_name: job_consumer
    working_dir: /app
    command: ["python3", "jobsearchsubul/tools/consumer.py"]
    depends_on:
      - kafka
      - postgres
    env_file:
      - .env
    volumes:
      - ./jobsearchsubul:/app/jobsearchsubul
      - ./backend:/app/backend

  prefect-server:
    image: prefecthq/prefect:2-python3.11
    container_name: prefect-server
    command: ["prefect", "server", "start", "--host", "0.0.0.0"]
    ports:
      - "4200:4200"
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
        
    volumes:
      - prefect_data:/root/.prefect


  prefect-agent:
    build:
      context: .
      dockerfile: jobsearchsubul/Dockerfile
    container_name: prefect-agent
    environment:
      PREFECT_API_URL: "http://prefect-server:4200/api"
      PREFECT_AGENT_QUEUE_NAME: "default"
    depends_on:
      - prefect-server
      - kafka
    command: >
      sh -c "echo 'Waiting for Prefect Server to be ready...' &&
      while ! curl -s http://prefect-server:4200/api/health >/dev/null; do
        sleep 5;
      done &&
      echo 'Creating deployment...' &&
      python3 jobsearchsubul/tools/deployment.py &&
      echo 'Starting Prefect agent...' &&
      exec prefect agent start -q default"
    volumes:
      - ./jobsearchsubul:/app/jobsearchsubul
      - ./backend:/app/backend



volumes:
  postgres_data:
  prefect_data: