"""Add cascade delete to lessons

Revision ID: 06d1bfdee0ef
Revises: f7e98981023d
Create Date: 2025-06-30 17:58:11.797903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d1bfdee0ef'
down_revision = 'f7e98981023d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.alter_column('subpart_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('video_subpart_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'subpart', ['subpart_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('video_subpart_id_fkey'), 'subpart', ['subpart_id'], ['id'])
        batch_op.alter_column('subpart_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
