"""added video_id to subpart

Revision ID: 09b3f249cb62
Revises: 
Create Date: 2025-06-30 14:51:25.506590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b3f249cb62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subpart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_id', sa.String(length=20), nullable=False))
        batch_op.drop_column('video_url')

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subpart_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('video_cert_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'subpart', ['subpart_id'], ['id'])
        batch_op.drop_column('cert_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cert_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('video_cert_id_fkey'), 'certification', ['cert_id'], ['id'])
        batch_op.drop_column('subpart_id')

    with op.batch_alter_table('subpart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('video_id')

    # ### end Alembic commands ###
