"""boto3 to access S3 for videos and lab guides+All crud fixes

Revision ID: 50f51005ce0b
Revises: a2b7dc066b9b
Create Date: 2025-06-17 04:13:45.129831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f51005ce0b'
down_revision = 'a2b7dc066b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cert_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'certification', ['cert_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cert_id')

    # ### end Alembic commands ###
