"""Add cascade delete to lessons

Revision ID: 5301647bccf2
Revises: 09b3f249cb62
Create Date: 2025-06-30 17:54:27.511011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5301647bccf2'
down_revision = '09b3f249cb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('lesson_certification_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'certification', ['certification_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lesson_certification_id_fkey'), 'certification', ['certification_id'], ['id'])

    # ### end Alembic commands ###
