"""Add is_admin to User

Revision ID: 62889e3ab3ee
Revises: 
Create Date: 2025-06-16 00:36:42.933389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62889e3ab3ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('job_cert_id_fkey'), type_='foreignkey')
        batch_op.drop_column('cert_id')
        batch_op.drop_column('url')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cert_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('job_cert_id_fkey'), 'certification', ['cert_id'], ['id'])

    # ### end Alembic commands ###
