"""Add cascade delete to lessons

Revision ID: ceabb9181a7a
Revises: dff93fd43f20
Create Date: 2025-06-30 19:09:48.230559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceabb9181a7a'
down_revision = 'dff93fd43f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_certifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_certifications', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
