"""Add cascade delete to lessons

Revision ID: dff93fd43f20
Revises: 06d1bfdee0ef
Create Date: 2025-06-30 18:00:33.449033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff93fd43f20'
down_revision = '06d1bfdee0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('cert_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('quiz_cert_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'certification', ['cert_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('quiz_cert_id_fkey'), 'certification', ['cert_id'], ['id'])
        batch_op.alter_column('cert_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
