"""Add cascade delete to lessons

Revision ID: e2298c993084
Revises: ceabb9181a7a
Create Date: 2025-06-30 19:12:28.322833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2298c993084'
down_revision = 'ceabb9181a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user_certifications', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_certifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('certification', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
