"""Add cascade delete to lessons

Revision ID: f7e98981023d
Revises: 5301647bccf2
Create Date: 2025-06-30 17:56:45.327684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e98981023d'
down_revision = '5301647bccf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subpart', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('subpart_lesson_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lesson', ['lesson_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subpart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subpart_lesson_id_fkey'), 'lesson', ['lesson_id'], ['id'])

    # ### end Alembic commands ###
